plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/BlockLength:
  Max: 32

Metrics/ClassLength:
  Max: 196

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 40

Metrics/PerceivedComplexity:
  Max: 16

Style/Documentation:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
