plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable

Metrics/ClassLength:
  Max: 196

Metrics/CyclomaticComplexity:
  Max: 12

Metrics/MethodLength:
  Max: 32

Style/Documentation:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 10

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 20

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false
